name: weather
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.2
  location: ^1.1.7
  shared_preferences: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/reindeer.png
  fonts:
    - family: WeatherIcons
      fonts:
        - asset: assets/weather_icons.ttf






